version: '3'
services:
    kanboard:
        build: Kanboard/
        ports:
            - "8084:80"
            - "443:443"
        volumes:
            - kanboard_data:/var/www/app/data
            - kanboard_plugins:/var/www/app/plugins
            - kanboard_ssl:/etc/nginx/ssl
        command: ["ls var/www/app/data"]
        links:
            - gitblit
    gitblit: 
        build: gitblit/
        ports: 
            - "8443:8443"
            - "8000:8080"
            - "9418:9418" 
            - "29418:29418"
    jenkins:
        build: jenkins/
        ports: 
            - "8080:8080"
            - "50000:50000"
        
        # /var/jenkins_home/
        # command:  rm -r ./var/jenkins_home
        volumes:
            - /var/wisestep/data/jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker
volumes:
    kanboard_data:
    kanboard_plugins:
    kanboard_ssl: